### PR TITLE
refactor(demo): Form components alignment - FRONT-953

### PR DESCRIPTION
**Pull request by planctus**
# PR description

Since this pr contains an update of the story-utils plugin, in order to test it you need to remove the node_modules folder and run yarn or you can manually move the index.js file in the src folder of the story-utils plugin into the package in the node_modules folder.

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

- [ ] I have put the vanilla component as `devDependencies`
- [ ] I have put the specs package as `devDependencies`
- [ ] I have added the components directly used in the twig file (with `include` or `embed`) as `dependencies`
- [ ] My component is listed in `@ecl-twig/ec-components`'s `dependencies`
- [ ] My variables naming follow the guidelines (snake case for twig)
- [ ] I have provided tests
- [ ] I have provided documentation (for the "notes" tab)
- [ ] If my local `yarn.lock` contains changes, I have committed it
- [ ] I have given my PR the proper label (`pr: review needed` to indicate that I'm done and now waiting for a review ,`pr: wip` to indicate that I'm actively working on it ...)

### CODE REVIEW

**Comment by Joosthe** [comment]
WARNING in ./src/ec/packages/ec-component-radio/radio.story.js 14:2-18
"export 'getFormItemKnobs' was not found in '@ecl-twig/story-utils' i still get this after a yarn install is theire something i am missing ?

**Comment by planctus** [comment]
You need to delete node_modules and run yarn or manually copy the index.js file in the src folder in the node_modules folder:
`cp utils/story-utils/src/index.js node_modules/@ecl-twig/story-utils/src/index.js`

**Comment by Joosthe** [comment]
Still get the error after:
`cp utils/story-utils/src/index.js node_modules/@ecl-twig/story-utils/src/index.js`

i had already tried:
`rm -rf node_modules && yarn install`

 i still get the error

**Comment by planctus** [comment]
Soooooorrrry, @Joosthe, now what i wrote is valid, before i haven't just copied myself the file from the node_modules folder to the one in the workingtree.. :D

**Pull request merged**
